# Generated by Django 5.1 on 2024-09-26 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='Brand',
            field=models.CharField(default='H&M', max_length=100),
        ),
    ]
