# Generated by Django 5.1 on 2024-09-29 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='main_category',
            name='link',
            field=models.CharField(default='home.html', max_length=200),
        ),
    ]
