# Generated by Django 5.1 on 2024-09-30 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_product_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
