# Generated by Django 5.1 on 2024-10-01 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_brand_product_color_product_filter_price_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='link',
            field=models.CharField(default='/', max_length=200),
        ),
    ]
