# Generated by Django 5.1 on 2024-10-23 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_category_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='description',
        ),
        migrations.RemoveField(
            model_name='product',
            name='featured_image',
        ),
    ]
