# Generated by Django 5.1 on 2024-10-24 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_main_category_link_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main_category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='main_category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
