# Generated by Django 5.1 on 2024-10-24 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_main_category_name_alter_main_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='color',
            name='product',
        ),
        migrations.RemoveField(
            model_name='filter_price',
            name='product',
        ),
        migrations.RemoveField(
            model_name='category',
            name='Main_category',
        ),
        migrations.RemoveField(
            model_name='category',
            name='image',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='brand',
        ),
        migrations.DeleteModel(
            name='color',
        ),
        migrations.DeleteModel(
            name='filter_price',
        ),
        migrations.DeleteModel(
            name='main_category',
        ),
    ]
