# Generated by Django 5.1 on 2024-10-24 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_alter_category_slug_alter_product_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='category',
            new_name='main_category',
        ),
    ]
