# Generated by Django 5.1 on 2024-10-29 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_product_image_delete_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/products/default.jpg', upload_to='media/products'),
        ),
    ]
