# Generated by Django 5.1 on 2024-10-29 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(default='media/slider_imgs/default.jpg', upload_to='media/slider_imgs'),
        ),
    ]
